apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
  namespace: identity
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  parentRefs:
    - name: public-gateway
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - keycloak.15.224.195.86.sslip.io
  rules:
    - backendRefs:
        - name: keycloak-keycloakx-http
          port: 80
