---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ionos-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    IONOS_PUBLIC_PREFIX: AgA+LkFg/w6C3p9X8UBg/3rMog+qxZTpcMUMWK2AdTPBzCvg8k0LPJDzVnJ3QkZ+zcV6lcS/TNU69sHTzxcbQzBgblyt1aiYjHVMH+uB0XnB6HQZ5sQmlsgCSdkbyaQhyM+p6Svv8wD2EW5z9NumtMTYP2NI/1zc9Lhhma24IVjpaG1lTPsqBsf8ct38Ej0xfqGqeA0Xt7R691JwsEKkFnHhIm5GBHd9sEAc5KjQYGaFNS9tpk1vj7gDBJxOfcsrfH3irG8OJjz1//xgnbgP6pfMOQgO9Mzu1N9EN2RC4to6qTlkyi3YffB8l8ZL8Ya6tTbBGkr6yzUF5Wt7dynopDs6c23pcyDQzf+5RxqUpXpQ60r/ARoS1ntWgK7ujMyvog0D/HAlf+sIUm/I5aN5ot5EqPPKd+JLbiaJIjAntboYGpRb1t2UOaNy5sQEtCQz60O3sL69c2WU+O1WFzdhpVmZQItB16dfSaZZe4cH72XJpjd72a9nxpW/MCxfkLBxzq7XonALhBPdCOI+9RDCDg9UuFX3DSQVZ7SDvdmUF4tWYIYVZ/K1qt1/AZ1SKroHrUTiu1emlMQnFlXhVlBaZ7QdvOXw4y2TEMvana8q7XRFvqQuhTXBmmpGvYf7RMDOSspYZfkDTQER2ZhyK/7SUPIdPykWTPdodE2l6NTnLS+ZkSL6TaiJh1lqj/wREfO0D9537o7FfWBD6TFA6i0dIU8NqhNHpF9qLtkAsLUQaeqitQ==
    IONOS_SECRET: AgBZEienbZHu1U9WtzVg0HoRh0kKu/zAmSkrmTLHW08+0MHpA3SJ2R9YZ8Bg2FJTL7l0weRQRQzlyoTzXSmH5DhHOUMMGKg9B1xC/523J8D6hGxIxUlWZIpkgRAtFQI6SfaDgXMrk68UvP3Y5keTXrVJf3qf6F4iKdfsHsEawPqq65wU1FW66FO+AYSiWqa7tYeIDU2l0b/shEtd0+5xFqzf341KgMQuGGgTwikQUALmTwg0WYxDY8dH+gfZsHh4tSPWedqvEAqZUv/mYODm0DOFB+bYCHC2mEmkJ40e8Kr2bj70nG3NXFLv5+xFR4Pp0dJjL8BtpVW6utGgKKrYd2RBe+qlN9ErYM/ih20Y4ftoExn/GKn43+7trGAKA6rbsiZwldyW1vtRpWZf75FE5kl96dFCW83T0wKwKyqdw4wL3/ISHYzBOPfiQqROuTETO2l5kQWMvuzZeiXgXUyBFxNO7A3WNE4TeN5nNa5tJRwfVwtZBKRJbNlf0l3fIdAb7bLAsKuQkeR7mybih482RAuFrQbajeUfQ2f3ZRWjksb0o7aW+blLb/rVZTSs4v0nYqSG40jeaYwg8zy+DyVifKhPt7akEVwFoGyBRbFFsWbBWR+56C6fWehFe28V8YtLtDmp44vo6CADl843K6r0oi+QwtJtsjNgfQ0XxkIGmcWfG2XfDSdlNyWdUqlV5CTrPpEdQ/tQ6besIVPROtxUZ2l/w58zlVedlF+EirRyZNAvrXxtCmiGCGVk6a9KOs99cG6Wyp2Mvg4ZoiLzXxm1b1w1NoFOS5Yq0mfs2b5y0DWfleWIGsSLYQ==
  template:
    metadata:
      name: ionos-secret
      namespace: cert-manager
    type: Opaque
