apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespaces.yaml
  - 10-envoy-gateway.application.yaml
  - 20-cert-manager.application.yaml
  - 30-public-gateway.yaml
  - 40-cluster-issuers.yaml
  - overlays/production
