data:
  url: https://argocd.15.224.195.86.sslip.io
  admin.enabled: "false"
  oidc.config: |
    name: Dex
    issuer: https://dex.15.224.195.86.sslip.io
    clientID: argocd
    clientSecret: $argocd-dex-client:clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
