data:
  url: https://argocd.bxota.com
  admin.enabled: "false"
  oidc.config: |
    name: Dex
    issuer: https://dex.bxota.com
    clientID: argocd
    clientSecret: $argocd-dex-client:clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
