---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    webhook-url: AgAtevD3ns1tzZTkEbqB0ycY50k6ZRqJnN2ohTNfh8brZRMfnnpkftxLL2NZbgpuinhTUtDXel14qTSzICH573xNjtJ7tWGd9zCze02jGNfsVzLOuDap+sj1V1UZ68Rd338nKgm1a9eb7+UfV7VSzIfxgosGdlWTU6CqNbgQVJoOaw6XMNOrUFBNoZOB2LP7QLvAN++6GRWXp/nNPsw3wxqwMDW5/NHrt1M7ZuX37geZn5dZy/pUsIf0bMJaGEVczyCxOK+HWfu4lr/vePq/Lv+ACqOKV319ZnE8/ZeWoLZFw620Gbm8Ae06BbBVU10yWoXR8L0wA5G6AtnWdW7KZ/FA9Vx76vnxPZAZl0lLk5qgNN0XSgXP/5891suJmS32TiDlqjO6ZoFyqGEUknfuHHe8AbRCvUK4CH5E5GNf/XOxTJ/GIsFXgbRcVK1T/BBpp91/ext+eZ9XerIc1fyb33qTCrvRNPVDKssVuNOkpALYzLdr5kjWj8KWTpP1ZtznV7ryZ9VQM6VyzuUpua11f2FNTKrwf52BWd/kpQZAoO5ulhN30xeUcjyUAoT3AsenesIORAujtfrfqADYXn3VyHRQz+IRDeCteZkvF7iMqMgye7uYnJBsCV2kcnwNcrGh1cre4omkb3O/jj6FGTFQcwS4BvIrCZTvoHr5Ug3xP211UAG24x5zQIUy/1G0mAIo1oic63f5t/1ziv7EGRXwpYkoIHRoark76UKgwl5v8JT+1JNHUsDOFxlsBFVBkh0=
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
