---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    webhook-url: AgBzXONE+2bVmlp+tx3OHyKlWZgzZEahs8CX+4vIxR0nKnrPi432MLkiZoLVZKo3WGYXBFwvoubRe2ox0v9PSo8gxWrQXLGYjl83fPn1Rd5K/v5TpRYN9GrqsB75vv7ahQC1Boi2hooH+L3w8uNU5XU/p0PljCGc5HGjEgLnrLJzmuSx7zM39wpXxgtp0j3CM4o+GTq1rQ4wXlIZq0S9VeUZvgaz0/0tAW6WPdMLbG/9L3XKa6b5m56DY65mJt5wyo0nXNap+jjeVnhgSWvSGVYJ3IjL7coZNcX1T/aJ9z40GSZBRAQwHdw4MRJtvxBsMHjQD4/XVx2a1F1jzcPFEX/DdWUVnAktAzZ0LdZpfxCHaIcTXBeWHjj1BVaAhzfApfkdyVdVT/eRPhpstCAE9tqAOZ3ZAobZAAZYlDp8vg4zMbANl9vgoM9m6HkAdapFpsSzXmnmSKLqh3ZyBOBTQh3hF8pFRJNxiQXXUYR309MRLXvPj6m77JStHpd1pkH/T6Nq7Qx4xe580Cb3YJNoxoT79YLyOMW7+lgoewSBA6xhcRLOBYWz3aScKSO7bczt+eaDFOn0DoOAi613oacKf1i3Z5fesVHlkmnq7RGpy1Asbg7R0TMObhFuMZzeG6d0jg4lDPWvTiptxmt97t60iZSPepVu9GWwOBGBNhy79xn4sxklGdoBxK+WN81uI+Sm+GymV3OhetwahyfgfqPUxvBJUIn+M6zDMJ8foB0bQexMJ6GvXialKqDMTmonaofI3dEUONmioJ5PxUuVvVsqwkxy1VhgKjgtt3NnE3Xxv21+UKdt8q70aOLm6IuK8ImkNP19UVvxrItN6Pzmid/mFlsRTuuyYA+YoEZc
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
