apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    chart: headlamp
    targetRevision: 0.45.0
    helm:
      releaseName: headlamp
      values: |
        config:
          oidc:
            secret:
              create: false
            callbackURL: https://headlamp.15.224.195.86.sslip.io/oidc-callback
            externalSecret:
              enabled: true
              name: headlamp-dex-client
              hasScopes: true
        env:
          - name: OIDC_CALLBACK_URL
            value: https://headlamp.15.224.195.86.sslip.io/oidc-callback
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
