apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespaces.yaml
  - 05-efs-bootstrap-loki.job.yaml
  - 10-loki-pv.yaml
  - 20-kube-prometheus-stack.application.yaml
  - 30-loki.application.yaml
  - 40-alloy.application.yaml
  - 50-headlamp.application.yaml
  - 60-routes.yaml
