---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-dex-client
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    clientSecret: AgBFAHUWvGJNn8HoD/7uNLKfoQ2Kjr8DHNp3VMY62mvr+7zjFgGXesn64+ttZtAtTX8Nofk30SNcJJwFLjvfkyHccrKR5nG7oupo9O6Doq7vgmCE3U96EEiTJwzAzCb7Reqh3RVGdDHP3SggQ7GTBBRo0h9rCnvJGdvLvzQSENu4Xj6P2Af2vKwAW1HtY7kea+pwHQd/xvNTa7jtu9galaB50/2DwPM3BhrL4bjyFqZgXj/F1EWb64a0Ge4g+MzuPxExo2OOOQqgte0Szybvi7om0nVKM5LZunmaMlUCbDCGYXg06iuj2gRiWGbj84u4h4alBiMsrpE5SUDBcL+whRXnFIms7mY3ZaxRPoG8RZcwL80apHQKMnhBchmbRUAMYNMdd0RUl5REF7Y8A9f6qF9CZFuHyMTR8jxaaVImiqPlbJzgXub1wVtEsW6BfA/pLrWqLrMeA9kHT9cmxnyG2nC6OlLZKKjajHfPiYXSSKae0OTem6+3SdRLBzX+QizQhMqqjsyfT9T1FEG7wQgKx11gAKjqg941oG7pkM7cv4Jsxb4bYqJmGbmQCTFZVcha/LULJnTfygek5hfmJhjrtPmgR+6STna0iMeCnYhoVBi98lpvUq3ZdVtno8jt0fLfVdTHgw8AnEGJqzp8cIpC4EgBC4p7zKJRrtkqkQ0luWFTXWZUcaNxBiOjz8EywWbH+z/5Pa9+x1prNNdGhHvSNk1EZWLJAK2HFPAowLSZ/ke/aJJhfQpqWYxkELt+u/JIaaUKorIki+wRyiBsDFGD0JrK
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-dex-client
      namespace: argocd
    type: Opaque
