---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-dex-client
  namespace: identity
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    clientId: AgA7IsIhMkWeD151Iz6zXGuNj/EYrOxFnwZOwLO5QipteP98sG0i4C9tKcJaC0wxKcFIG0MgBD6gWLLAfP0WFu3523W6doIs+0bd7j1ifwjiEfWeZLgz+V5/sOqz3w0ypoFLx0Uq2NapLzH6LMvJLzz/E84t/vJHmJXDIWEEJ+L07vMiN4sfQ+f1D0ldvAYN5ViHpHdVmvmKQWzTWFoe+1ZmuhCAX4xfRqbOE2Mwq4+rsqotlVOEXB0axEN/aJSkvJOFm6NxrBnJGXaCuh25597bwmXVmDENTRvOT8Bh4NWbLp63GOa3alnH7ReZrEIYftdnIJk9gqsW6RysoNn+kJu1NBhvS8zsTYVtLyOVPIijt8iPzy36WuYkzh6DLu8S6oMAqNVzxhWILRwEn1DiJ3gzQ+Fa8n8Lu0jrz6C0VWyhZkkYmIINulzluXGZVwtoQOmoWzLFRlW+NXHRShjyaNGcbIjhUR1hMdpp5gWrqI6UWbfsomIoGnyxT3ujLSStpHV/0CVfr1L0ExcnfshNUGz/MMmBNrYWjqvWxd15KS/LOLP0TGPFs1SPqJFPYvWyFYnrxWpU+LMqdrCtPaoifoih5jCvjZKuQbi+6xgExdGRWUvt499WOXQlxooWsstjKnkoqmxCb8MF9CBnzwchxDlu3t9uGHsFNwGOqnAT8SdOYaTSq2dj9xuRP/UiJ0se2UVfoKOd/ws9
    clientSecret: AgCc+doXBceURRlxou1HN/rCTJ/cDQ9J9y/T8/+bnPY5Vpaboug3JXgBSLmGXXVWUmS8yea/g4qrivcamzq7caNXqsUg8kwWTTpISD4EPezwQBoFwOBCw/NbW8vB5F98djMzVf2DKBTEDWctJxFtN2WpUYQ/r0CvBlIhQy6mHj1RcZo5gikyHW+bum8H3I8JPGWEoxr7uPqdaujYDW+7l72mIyRhGWrMOqcd5vUxj9ETYRIPmr6LWzguYUffIABvTj7sRuIG0oVRS3chvDEgWC6Mxt+0tzC0gRu+kvVJXlhlFnHsbKBsTkWifP3H57y31vD7IscgakubJikWP+ItDazQEz6cZqNUWKvhFBmbxQXlWbIye8OsTqPU3shT5EfXg1cgMkefRR2AoTv6SZM/A3qtedj1lys1jWwV9fr3vq1aVIx+BFEMBbehgWGKLDvNfduWUUfh1217E0pZJwI2bBsRWM8L/Xwy7qFf5rQ+Bi9DANCGR5TxFWziiwvoYJ2fpwBFnfM8+QvtcSsNMb9Hyz3Ju2tF6nbCM9FWKh/CDNF6tu12YW25o/lENnbF+mOzpBeX9Qr+DiKMMVNHYMCfTMN3irbkqZZH4pPxf77eIDVPajjfWn5FFtLYBFa1K3mOqVF+wD0SU+Y1qBX1ngUv7N/Rw9FZiKw81oYvOnsJbvauQUUyWJ07OGk7rmyGQDQ4E1rLVoUaYYZ+G2cPvGGWnaIlSxnSKzxXyfvpJ2OgTnnCY4npyiGwtpZzFgz1pYhiCMLIsn8ydthADiLbi6oRg+NH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: grafana-dex-client
      namespace: identity
    type: Opaque
