---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headlamp-dex-client
  namespace: identity
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    clientId: AgCZUylGNVI89fFweYBgvY176iJKwn5voaG18Tuyv55vhyTdaCV/ba04BNLXVoLf/0NyiGi31IuhnBml67lDJLStIkoESvf7jiHCHiODVNO5PTFGceL7CzWT3AKIML+cxcM0XHcjTadLUvHxjSaIVgiGHQF2QnJuIeS0/oTnHNZmtlKLlsBOLUHvO/VEqrtMEI7tynP+5k6ABT6UHycOy5QapV4W7ioBETZYZAUX1SBJYbCgwHzf9jWsJ5ahrUnj4vQ8TYH5iXk064gxQ+adesevX+JE5QG/p9pfHLtFi55ZpXc/Gl3kze8akpxx3tMqVlpOiCBN8rcE1gP7omPRzdZDIRV5l0XOwfiFQaImXCeiNZoXSeRIasxTxIOTlTyQ05/DH5CzFvkyNWt88SavwlB6J881b/nLaDAPpWHAdQVMu+iv575HQaQjxAuuM79+C1Td6i3ZrDBntXsiDwwhijMeu2/mMOQytv7Pgwde9/6+M987LVFaGwXsxFe1d1fXS1zJ+YZwNPsCZ+i/BnIXBeUzqtyrIxpxZpSjsQWSsih3vz2B8Wij6M/rSJrW1qKx6QmLPYHtWd/B/eT7D3XaE6hu3vf2WFJy4JYaxUB1EJcTUStGLuLADA3tVMfgvN4Dgf3o4e7ZGvnO+8jj22mKiwPTfZeEGzQIhAMWJT2+BpZ1B4mEUACXWuVMRqO/sekZBRcO7drqEfN9sQ==
    clientSecret: AgAFWCvrSrdIDBswPLB02GKmlJgVzDArxFLxJw5CCJKYZLbo6Wygj4eGrb9t0Sr0F+lQJrBy63F4WdkP8wxXDJPbvkLNCDM6Ndru/Vhr41LjbLQCT381xELOBWCWh44WzMtp04ycvllx9JGk0LLEY+BvMwSCeDIxVSZWajufwuCoSDBwaP1vBKjaSEM/l3Py2QUrm3h48tmu3scNv8lyFAvHz20gZ2DLeW0kkDDwWrwn6EY03tYtfn+hQJrcbrF8Ib2rGemWEb/fjjLew72R58ZT55xwgGdSr184BJAygR/NV7g00Zr3bxTadGx//1xm65Fc0isclhceMwFrP2HmHacsHR0wgiMp6UihmjK7zX4MOMGo0R+vGkcs9mMJ0wKJf6nvPAkEYgeVJlQ59HTRt8aQrOaWDoxgsz7RS5fzsonsSHPg4kULU4gNaxzL7bilAD9ZDLtmRFvchBGbQPYsL3phExC12itGcle6SvBjxkVt8FajW0LeVAPGa4kmkoh0WXEyX2QpxEPVWp/3t7N9P5apuIvc4gZ2D/mLu8k8elvtu2YoxATfKr+4HJRDVz9x0jiN2mKLemwP+vlQ9nDplGBPFhScoSATEDg1uLCIU2U1cLPaQK1flMPb/JE0VN6a5ArPDgxk1sJFS0HKWWOFqriHBsbyTdyxNs1FYvd8XWwZdgV/m1IXpzYXyETD53+bt2CSFwgLzNEVKE0sQblk4VdOLzG+O1KNe7IhrDarXoKX+zMMs3EervnEDi8d71Iwmi0lLcfPm78ZZt17AQDUMnOG
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: headlamp-dex-client
      namespace: identity
    type: Opaque
