---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: identity
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    password: AgCCWAt8422pHfNoc1YzfQgO/UglbXLf2A1j+laFUQPP+/i7mg5MKt1I8G0hw8j31+OoBEZ3ziJ3FnNhToKSSpKL8mpM6UBm0k3XAkBea3XtW4Ocr9x8IBRAk8/lS9VGukTSYew0M+HH988oQiZ/aUTTPIuIwEuqkSrNix2SH3qORRI+kjxjMg1/xbuKQyTXoJcbMdiB5kS52FEEvtWY17rTsAaV+gVEFizq4y5iBCYhv1sWpnwe1+Rja+l2DwFDV+vk2gswxtNtNJRnot3Izp62vXOzgy9jEWHgAcbetMrEmYelpHUf8aXqbGO/idBNDp+HR+cqx6ZYK0SIyaqHciCKh89wniaW/nVv2+jJwS0Yk/HswTnXmJkzJMYsAvk5VHARQML8wU1w8qO+DcoAe267eDmj/4kwxokOGGOAyDZrYolxFk/MKVSi+ddn/3psHNkt+hNoxPIM9BOzjGFxILBIqyQQwbmYvilm1ZMcYQTL6e0s+l3C4GZP51rEdTBgCmhCbQHgtCYVnG+NZgTFQt+pnazkCCNAbKfhO9XLqGoBTVvT3KVITshGRwWTWYPCQTPtMJaZMzhKNkAiH8HyIwlbPd6A0MO7lorFnHdzP6ytguI6ZX3WkEXCz6LJtcAE2oOsYIAbEADqaGoqvQFBip7GZtuUn4waRSy1RF3jn5+JVCam9ynONDVh9SsC90PGnm40ijS9TLvyEGIw1pKu3ZnK0oHiB0pCf74xvwY1RMZiwA==
    username: AgBUBRLTwaXcij0s8bxc5q08HfrLYvS2A+pP95uE4aTDRb02x+hSoOP+63OxytTC5sP8cOx5WRZIqxMChLk5brvuQpgfD2tJyO5vNzyrPadciOlbwm5EpvEQtws2qg6KzflVXRhoI6hrHPEhW6BWxluSPD8WjVZXLbFyDg5zIZlfyNg2x5WrNjrpKWMJh3u9psT4b3+LBlK4KpSYqtBj5RoWwDTXUXtNwmPC4wJ7dzlly43lea3QLqh3d7QmI++vut/gPTgCS/+EJQ18e3UalWtIY8fjmYzAQ4s0+cS004Yt8igTW2+/kw/TS3WNgTKFbmRuzTfblrz9SdVnE1EzUvH4o3w76vk7u9IHlip7iQUDwi7JwaToci4d4JQjCoz/9//RrtkCwlNiOEdLnELLKcsMQ5SxdY2gbUHlAr6y0o5CVaZ3FKXo6CZWtFxIsccQB5CroRX40kEImgNJsb9qSlp/VNCqYgqnwZ7YEnK+j3EI/DAr5wya9auX9+/7Sy5P0M1+TuvW1XTjb6fjJZzIjY/BX7E1ANtcDxBKfmJ6vgUrMcrgFA91vqqGSoqxRwU3fcbD+qHbwjjxycJ7O8YzZbxju7/kvscFQYkIJNeB7ps9s9UEg7PVaVe6nrciA48L4CEt2yAK09lR/gAiJjPKizYvjxGhOdtV9neHrV+BJNjTTO0zAuiUBNZOZ6Rn8EAzJ81KJjGi2Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: keycloak-admin
      namespace: identity
    type: Opaque
