apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - keycloak-admin.sealedsecret.yaml
  - keycloak-realm-config.sealedsecret.yaml
  - dex-config.sealedsecret.yaml
  - argocd-dex-client.sealedsecret.yaml
  - grafana-dex-client.sealedsecret.yaml
  - headlamp-dex-client.sealedsecret.yaml
